spring:
  application:
    name: KNU_Scraping

  data:
    redis:
      host: localhost
      port: 6379

  webhook:
    computer_science_and_engineering: ${computer_science_and_engineering}
    knu_academic: ${knu_academic}


